# Generates the public application catalog from the validated JSON source.
[CmdletBinding()]
param(
    [string] $OutputPath,
    [switch] $Check
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$moduleRoot = Join-Path $projectRoot 'src\modules'

Import-Module (Join-Path $moduleRoot 'Application\CatalogService.psm1') -Force
Import-Module (Join-Path $moduleRoot 'Infrastructure\JsonCatalogRepository.psm1') -Force

function ConvertTo-KapselMarkdownCell {
    [CmdletBinding()]
    param([AllowNull()] [object] $Value)

    if ($null -eq $Value) { return '-' }
    $text = ([string] $Value).Trim() -replace '\r?\n', ' '
    if ([string]::IsNullOrWhiteSpace($text)) { return '-' }
    return $text -replace '\|', '\|'
}

function ConvertTo-KapselMarkdownCode {
    [CmdletBinding()]
    param([AllowNull()] [object] $Value)

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string] $Value)) { return '-' }
    $tick = [char] 96
    $text = (ConvertTo-KapselMarkdownCell -Value $Value) -replace $tick, "$tick$tick"
    return "$tick$text$tick"
}

function New-KapselCatalogMarkdown {
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)] [object] $Snapshot)

    $lines = New-Object 'System.Collections.Generic.List[string]'
    $lines.Add('# Kapsel Application Catalog')
    $lines.Add('')
    $lines.Add('<!-- Generated by scripts/Generate-CatalogMarkdown.ps1. Do not edit manually. -->')
    $lines.Add('')
    $lines.Add('This catalog is generated from the validated `src/applications.json` source.')
    $lines.Add('')
    $lines.Add("**$($Snapshot.Counts.Applications) applications across $($Snapshot.Counts.Categories) categories.**")

    $categories = @($Snapshot.Categories | Where-Object { $_ -ne 'All' } | Sort-Object)
    foreach ($category in $categories) {
        $applications = @(
            $Snapshot.Applications |
                Where-Object { $_.Category -eq $category } |
                Sort-Object -Property Name, Key
        )
        $lines.Add('')
        $lines.Add("## $(ConvertTo-KapselMarkdownCell -Value $category)")
        $lines.Add('')
        $lines.Add('| Application | Description | FOSS | winget | Chocolatey | Website |')
        $lines.Add('| --- | --- | :---: | --- | --- | :---: |')

        foreach ($application in $applications) {
            $name = ConvertTo-KapselMarkdownCell -Value $application.Name
            $description = ConvertTo-KapselMarkdownCell -Value $application.Description
            $foss = if ($application.Foss) { 'Yes' } else { 'No' }
            $winget = ConvertTo-KapselMarkdownCode -Value $application.WingetId
            $choco = ConvertTo-KapselMarkdownCode -Value $application.ChocoId
            $link = ConvertTo-KapselMarkdownCell -Value $application.Link
            $website = if ($link -eq '-') { '-' } else { "[Open]($link)" }
            $lines.Add("| $name | $description | $foss | $winget | $choco | $website |")
        }
    }

    return ($lines -join "`n") + "`n"
}

$catalogDocument = Read-KapselApplicationCatalogDocument
$snapshot = New-KapselCatalogSnapshot -CatalogDocument $catalogDocument
$markdown = New-KapselCatalogMarkdown -Snapshot $snapshot
$resolvedOutputPath = if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    Join-Path $projectRoot '.github\CATALOG.md'
}
elseif ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $OutputPath
}
else {
    Join-Path $projectRoot $OutputPath
}

if ($Check) {
    if (-not (Test-Path -LiteralPath $resolvedOutputPath -PathType Leaf)) {
        throw "Generated catalog is missing: $resolvedOutputPath"
    }

    $current = [System.IO.File]::ReadAllText($resolvedOutputPath) -replace "`r`n", "`n"
    if ($current -ne $markdown) {
        throw 'Generated catalog is outdated. Run npm run docs:catalog and commit the result.'
    }
    Write-Host "Generated catalog is current: $resolvedOutputPath"
    return
}

$outputDirectory = Split-Path -Parent $resolvedOutputPath
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($resolvedOutputPath, $markdown, $utf8WithoutBom)
Write-Host "Generated catalog: $resolvedOutputPath"
